$file = 'g:\My Drive\IronWall-Gamethon\frontend\attacker.js'
$lines = Get-Content $file -Encoding UTF8

$newLines = @(
    "// ── Audio Engine (Cyber-Synth) ──────────────────────────────────────────────",
    "class CyberSynth {",
    "    constructor() { this.ctx = null; this.enabled = false; }",
    "",
    "    init() {",
    "        if (this.ctx) return;",
    "        try { this.ctx = new (window.AudioContext || window.webkitAudioContext)(); this.enabled = true; }",
    "        catch (e) {}",
    "    }",
    "",
    "    // freq=start, endFreq=end, type=wave, vol, dur=seconds, delay=start offset",
    "    _tone(freq, endFreq, type, vol, dur, delay = 0) {",
    "        const ctx = this.ctx, now = ctx.currentTime + delay;",
    "        const osc = ctx.createOscillator(), gain = ctx.createGain();",
    "        osc.type = type;",
    "        osc.frequency.setValueAtTime(freq, now);",
    "        if (endFreq !== freq)",
    "            osc.frequency.exponentialRampToValueAtTime(Math.max(endFreq, 1), now + dur);",
    "        gain.gain.setValueAtTime(vol, now);",
    "        gain.gain.exponentialRampToValueAtTime(0.001, now + dur);",
    "        osc.connect(gain); gain.connect(ctx.destination);",
    "        osc.start(now); osc.stop(now + dur + 0.01);",
    "    }",
    "",
    "    play(type) {",
    "        if (!this.enabled || !this.ctx) return;",
    "        if (this.ctx.state === 'suspended') this.ctx.resume();",
    "        switch (type) {",
    "",
    "            // Crisp laser ZAP",
    "            case 'fire':",
    "                this._tone(1200, 180, 'sawtooth', 0.28, 0.18);",
    "                this._tone(600,  90,  'square',   0.12, 0.14);",
    "                break;",
    "",
    "            // Harsh electric DENIED buzz",
    "            case 'blocked':",
    "                this._tone(380, 380, 'square',   0.30, 0.07);",
    "                this._tone(760, 760, 'sawtooth', 0.20, 0.07, 0.09);",
    "                this._tone(380, 380, 'square',   0.25, 0.07, 0.20);",
    "                break;",
    "",
    "            // SQL — descending digital glitch crunch",
    "            case 'sql':",
    "                this._tone(950, 280, 'sawtooth', 0.25, 0.14);",
    "                this._tone(475, 140, 'square',   0.13, 0.10, 0.07);",
    "                break;",
    "",
    "            // XSS — sharp high-freq injection ZAP",
    "            case 'xss':",
    "                this._tone(2600, 700, 'sine', 0.22, 0.10);",
    "                this._tone(1800, 400, 'sine', 0.16, 0.08, 0.06);",
    "                break;",
    "",
    "            // DDoS — rapid stutter burst",
    "            case 'ddos':",
    "                for (let i = 0; i < 7; i++)",
    "                    this._tone(700, 700, 'square', 0.18, 0.035, i * 0.055);",
    "                break;",
    "",
    "            // Zero-Day — deep ominous rising siren",
    "            case 'zero':",
    "                this._tone(60,  500, 'sawtooth', 0.32, 0.30);",
    "                this._tone(120, 900, 'sine',     0.18, 0.28, 0.04);",
    "                break;",
    "",
    "            // Phishing — deceptive 3-note chime",
    "            case 'phish':",
    "                this._tone(1046, 1046, 'sine', 0.22, 0.07);",
    "                this._tone(1318, 1318, 'sine', 0.20, 0.07, 0.09);",
    "                this._tone(1046, 1046, 'sine', 0.14, 0.10, 0.18);",
    "                break;",
    "",
    "            default:",
    "                this._tone(900, 200, 'sawtooth', 0.22, 0.15);",
    "        }",
    "    }",
    "}"
)

# Lines 33-80 are index 32-79 (0-based). Replace those lines.
$result = $lines[0..31] + $newLines + $lines[80..($lines.Count - 1)]
Set-Content -Path $file -Value $result -Encoding UTF8
Write-Host "Done. New line count: $($result.Count)"
